pipeline {
    agent any
    stages {
        stage('Build Frontend') {
            steps {
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/Diego9028/Ev1']])
                dir("kartingrm-frontend"){
                    bat 'npm install --legacy-peer-deps'
                    bat 'npm run build'
                }
            }
        }

        stage('Build and Push Docker Image') {
            steps {
                dir("kartingrm-frontend"){
                    script {
                        withDockerRegistry(credentialsId: "docker-credentials"){
                            bat 'docker build -t diego9028/kartingrm-frontend .'
                            bat 'docker push diego9028/kartingrm-frontend'
                        }
                    }
                }
            }
        }
    }
}
